### ISSUE TITLE
关于公招功能的功能与接口分享

### ISSUE THREAD

**Issue by Eigh18n** [vivien8261/Amiya-Bot#1]
### 或许可以让Amy增加一个公招分析功能？
我自己找了一个**公招分析的数据接口**
但是，**我不会写qaq**
_（菜鸡爬了）_
这里希望Amy能实现这个功能
  
## 接口
https://www.bigfun.cn/static/aktools/【最新版本】/data/akhr.json
其中的**最新版本**要从[bigfun明日方舟工具箱](bigfun)获取
我使用正则来获取
`<script src="/static/aktools/(\d+)/js/runtime-es2015.js" type="module">`

## 想法
因为一般玩家对公招三星的结果不感兴趣
或许功能应该返回**必出四星的tags组合**？

## 补充
在2020/12/12晚7点时
最新版本为1604978022

[bigfun]: https://www.bigfun.cn/tools/aktools/

**Comment by Eigh18n** [comment]
不用去重，mysql里我记得有个in方法，就是一个tag在不在这个数组里，实在不行用like也行，最后遍历所有tag的结果集求个内链接
——群大佬『鹤望兰号』（412459523）

**Comment by vivien8261** [comment]
@Eigh18n 
公招功能一直鸽其实是因为不知道怎么让用户去使用，昨天想想，用 [图像识别](https://cloud.baidu.com/doc/OCR/s/7kibizyfm) 解决了<br>
关于怎么查询，其实用like就可以解决了，识别出tags的列表之后，生成类似以下的sql

```mysql
SELECT *
FROM t_operator_tags_relation
WHERE (operator_tags LIKE "%防护%" OR operator_tags LIKE "%输出%" OR operator_tags LIKE "%生存%")
  AND operator_rarity >= 1
  AND operator_rarity <= 5
ORDER BY operator_rarity DESC
```

然后再分析结果就行，新的数据库结构等下会更新到release
