### ISSUE TITLE
简单的问题

### ISSUE THREAD

**Issue by vivien8261** [vivien8261/Amiya-Bot#5]
简单的不需要的新建issue的问题，可以在这里提问 (๑*◡*๑)

**Comment by Eigh18n** [comment]
好耶！

**Comment by TNXG** [comment]
有没有QQ群doge

**Comment by vivien8261** [comment]
> 有没有QQ群doge

@TNXG 362165038

**Comment by nightmare-yudachi** [comment]
使用pip安装graiax-silkcoder时报错
ERROR: Could not build wheels for graiax-silkcoder which use PEP 517 and cannot be installed directly

**Comment by Initial-heart-1** [comment]
> 使用pip安装graiax-silkcoder时报错
> ERROR: Could not build wheels for graiax-silkcoder which use PEP 517 and cannot be installed directly

https://stackoverflow.com/questions/64038673/could-not-build-wheels-for-which-use-pep-517-and-cannot-be-installed-directly
提issues前先善用互联网查找

**Comment by Initial-heart-1** [comment]
> > 使用pip安装graiax-silkcoder时报错
> > ERROR: Could not build wheels for graiax-silkcoder which use PEP 517 and cannot be installed directly
> 
> https://stackoverflow.com/questions/64038673/could-not-build-wheels-for-which-use-pep-517-and-cannot-be-installed-directly
> 提issues前先善用互联网查找

译：你确定你python版本是对的？
建议使用python3.7

**Comment by vivien8261** [comment]
> 使用pip安装graiax-silkcoder时报错
> ERROR: Could not build wheels for graiax-silkcoder which use PEP 517 and cannot be installed directly

windows 下安装需要电脑有 C 运行库或安装 vs build tools，这个暂时没找到其他解决方法

**Comment by Initial-heart-1** [comment]
> > 使用pip安装graiax-silkcoder时报错
> > ERROR: Could not build wheels for graiax-silkcoder which use PEP 517 and cannot be installed directly
> 
> windows 下安装需要电脑有 C 运行库或安装 vs build tools，这个暂时没找到其他解决方法

az，我没装也行来着......

**Comment by GodotL** [comment]
自己部署的兔兔每天的第一次签到都提示已经签完了是什么情况啊，俺这边的群友都说这个兔兔不保熟了（）

**Comment by MistEO** [comment]
兔兔生气是不是没有做？好像`user_mood`只有读没有写来着

**Comment by puzi12138** [comment]
请问好几天签到都是已经签到，没有刷新是怎么回事

**Comment by GodotL** [comment]
> 请问好几天签到都是已经签到，没有刷新是怎么回事

跟兔兔私聊【维护】进行手动维护，如果不是挂服务器的话那个每天早上四点自动维护的功能是没用的

**Comment by puzi12138** [comment]
> > 请问好几天签到都是已经签到，没有刷新是怎么回事
> 
> 跟兔兔私聊【维护】进行手动维护，如果不是挂服务器的话那个每天早上四点自动维护的功能是没用的

多谢

**Comment by puzi12138** [comment]
再问一下加群加不进，申请好几天了

**Comment by Initial-heart-1** [comment]
> 兔兔生气是不是没有做？好像`user_mood`只有读没有写来着

确实没有做，万年33
当初我反馈群一堆用户刷了几千条，兔兔面不改色

**Comment by Eigh18n** [comment]
> 再问一下加群加不进，申请好几天了

大概率是tx屏蔽了你的申请，一般我放假时会去看的。

**Comment by chaggle** [comment]
请问您是否有考虑过优化查询明日方舟专精材料，类似于下图这种一次性给出多技能的从专一到专三的材材料？
![QQ图片20220415120525](https://user-images.githubusercontent.com/47071009/163516529-60add27b-2a4d-4667-92b6-11f1cf25c91d.jpg)

**Comment by Initial-heart-1** [comment]
曾给出过提议，且已在 issues 内，处于 open 状态。（#54）

**Comment by SANaoi** [comment]
启动 AMIYA-BOT.EXE 最后出现[ERROR] Http <release> response: {'code': 3, 'msg': 'Session失效或不存在'} 可以在cmd里看见bot发出的消息及接收群友的消息 但就是发不到群里

**Comment by 2038964352** [comment]
> 一开始可以发出去一两次, 后来我也遇到了这样的问题

**Comment by 2038964352** [comment]
> 启动 AMIYA-BOT.EXE 最后出现[ERROR] Http response: {'code': 3, 'msg': 'Session失效或不存在'} 可以在cmd里看见bot发出的消息及接收群友的消息 但就是发不到群里

也遇到了相同的问题, 一开始的启动完毕可以发送, 但是信息只在cmd里面.

**Comment by HYY1116** [comment]
> > 启动 AMIYA-BOT.EXE 最后出现[ERROR] Http response: {'code': 3, 'msg': 'Session失效或不存在'} 可以在cmd里看见bot发出的消息及接收群友的消息 但就是发不到群里
> 
> 也遇到了相同的问题, 一开始的启动完毕可以发送, 但是信息只在cmd里面.

尝试将mirai-http-api回退至2.4.0，我这样成功解决了这个问题

**Comment by Narushio** [comment]
兔妈，qq群怎么无了

**Comment by Eigh18n** [comment]
> 兔妈，qq群怎么无了

我也刚想问，速速fork库

**Comment by Narushio** [comment]
> 速

我猜兔妈做api测试把群直接整没了

**Comment by MistEO** [comment]
> > 速
> 
> 我猜兔妈做api测试把群直接整没了

被 tx 一锅端了

**Comment by hongshiyu** [comment]
求问，无法连接websocket如何解决，是ws不再支持的原因吗

**Comment by BoBppy** [comment]
请问怎么主动授权群微博推送

**Comment by Initial-heart-1** [comment]
![image](https://user-images.githubusercontent.com/63091661/176990893-1bda9fc8-ea76-4d76-81db-ba1ff7b641b1.png)

此开关

**Comment by yorisona** [comment]
centos7.6 可以部署吗

**Comment by vivien8261** [comment]
> centos7.6 可以部署吗

不支持 centos

**Comment by ZhaoZuohong** [comment]
> centos7.6 可以部署吗

可以用 Docker

**Comment by yorisona** [comment]
> > centos7.6 可以部署吗
> 
> 可以用 Docker

有docker部署的文档嘛

**Comment by ZhaoZuohong** [comment]
> > > centos7.6 可以部署吗
> > 
> > 
> > 可以用 Docker
> 
> 有docker部署的文档嘛

1. 安装 Docker：<https://docs.docker.com/engine/install/centos/>
2. 国内服务器可能要换源之类的
3. `docker run -it --network=host --name=amiyabot ubuntu:focal` 运行 Docker 容器
4. 在容器中 `apt update && apt install git python3-pip`
5. `cd / && git clone https://github.com/AmiyaBot/Amiya-Bot && cd Amiya-Bot`
6. 可以装个 `nano` 或者 `vim` 之类的，改一下 `requirements.txt`，把 `amiyabot` 改成 `amiyabot==1.1.19`
7. 也可以顺便改一下服务器的配置（`config/server.yaml`）
8. `pip3 install -r requirements.txt`
9. `playwright install --with-deps chromium`
10. `python3 amiya.py` 运行

快捷键 `Ctrl-P Ctrl-Q` 断开与容器的连接，`docker attach` 连接容器，`docker exec` 可以在容器里运行别的命令。`docker cp` 可以把文件在容器和宿主之间移动。如果容器停了，可以用 `docker start -ai amiyabot` 连上。
可以把宿主上的 `Amiya-Bot` 文件夹挂载到容器里（比如 `-v xxxx:/Amiya-Bot`）
参数 `--network=host` 比较偷懒；指定 `amiyabot==1.1.19` 是因为昨晚更新了 `amiyabot==1.1.20`，和现在的 master 不兼容，等更新就不用了。
如果感觉参数比较多，可以写个 compose file
有个 `mcr.microsoft.com/playwright:v1.27.1-focal` 容器可以试试

**Comment by yorisona** [comment]
> 

emmm我是说docker部署amiya的文档,我的服务器上有docker了(

**Comment by yorisona** [comment]
> > > > centos7.6 可以部署吗
> > > 
> > > 
> > > 可以用 Docker
> > 
> > 
> > 有docker部署的文档嘛
> 
> 1. 安装 Docker：https://docs.docker.com/engine/install/centos/
> 2. 国内服务器可能要换源之类的
> 3. `docker run -it --network=host --name=amiyabot ubuntu:focal` 运行 Docker 容器
> 4. 在容器中 `apt update && apt install git python3-pip`
> 5. `cd / && git clone https://github.com/AmiyaBot/Amiya-Bot && cd Amiya-Bot`
> 6. 可以装个 `nano` 或者 `vim` 之类的，改一下 `requirements.txt`，把 `amiyabot` 改成 `amiyabot==1.1.19`
> 7. 也可以顺便改一下服务器的配置（`config/server.yaml`）
> 8. `pip3 install -r requirements.txt`
> 9. `playwright install --with-deps chromium`
> 10. `python3 amiya.py` 运行
> 
> 快捷键 `Ctrl-P Ctrl-Q` 断开与容器的连接，`docker attach` 连接容器，`docker exec` 可以在容器里运行别的命令。



> > > > centos7.6 可以部署吗
> > > 
> > > 
> > > 可以用 Docker
> > 
> > 
> > 有docker部署的文档嘛
> 
> 1. 安装 Docker：https://docs.docker.com/engine/install/centos/
> 2. 国内服务器可能要换源之类的
> 3. `docker run -it --network=host --name=amiyabot ubuntu:focal` 运行 Docker 容器
> 4. 在容器中 `apt update && apt install git python3-pip`
> 5. `cd / && git clone https://github.com/AmiyaBot/Amiya-Bot && cd Amiya-Bot`
> 6. 可以装个 `nano` 或者 `vim` 之类的，改一下 `requirements.txt`，把 `amiyabot` 改成 `amiyabot==1.1.19`
> 7. 也可以顺便改一下服务器的配置（`config/server.yaml`）
> 8. `pip3 install -r requirements.txt`
> 9. `playwright install --with-deps chromium`
> 10. `python3 amiya.py` 运行
> 
> 快捷键 `Ctrl-P Ctrl-Q` 断开与容器的连接，`docker attach` 连接容器，`docker exec` 可以在容器里运行别的命令。

emmm我是说docker部署amiya的文档,我的服务器上有docker了(

**Comment by ZhaoZuohong** [comment]
> > > > > centos7.6 可以部署吗
> > > > 
> > > > 
> > > > 可以用 Docker
> > > 
> > > 
> > > 有docker部署的文档嘛
> > 
> > 
> > 
> > 1. 安装 Docker：https://docs.docker.com/engine/install/centos/
> > 2. 国内服务器可能要换源之类的
> > 3. `docker run -it --network=host --name=amiyabot ubuntu:focal` 运行 Docker 容器
> > 4. 在容器中 `apt update && apt install git python3-pip`
> > 5. `cd / && git clone https://github.com/AmiyaBot/Amiya-Bot && cd Amiya-Bot`
> > 6. 可以装个 `nano` 或者 `vim` 之类的，改一下 `requirements.txt`，把 `amiyabot` 改成 `amiyabot==1.1.19`
> > 7. 也可以顺便改一下服务器的配置（`config/server.yaml`）
> > 8. `pip3 install -r requirements.txt`
> > 9. `playwright install --with-deps chromium`
> > 10. `python3 amiya.py` 运行
> > 
> > 快捷键 `Ctrl-P Ctrl-Q` 断开与容器的连接，`docker attach` 连接容器，`docker exec` 可以在容器里运行别的命令。
> 
> > > > > centos7.6 可以部署吗
> > > > 
> > > > 
> > > > 可以用 Docker
> > > 
> > > 
> > > 有docker部署的文档嘛
> > 
> > 
> > 
> > 1. 安装 Docker：https://docs.docker.com/engine/install/centos/
> > 2. 国内服务器可能要换源之类的
> > 3. `docker run -it --network=host --name=amiyabot ubuntu:focal` 运行 Docker 容器
> > 4. 在容器中 `apt update && apt install git python3-pip`
> > 5. `cd / && git clone https://github.com/AmiyaBot/Amiya-Bot && cd Amiya-Bot`
> > 6. 可以装个 `nano` 或者 `vim` 之类的，改一下 `requirements.txt`，把 `amiyabot` 改成 `amiyabot==1.1.19`
> > 7. 也可以顺便改一下服务器的配置（`config/server.yaml`）
> > 8. `pip3 install -r requirements.txt`
> > 9. `playwright install --with-deps chromium`
> > 10. `python3 amiya.py` 运行
> > 
> > 快捷键 `Ctrl-P Ctrl-Q` 断开与容器的连接，`docker attach` 连接容器，`docker exec` 可以在容器里运行别的命令。
> 
> emmm我是说docker部署amiya的文档,我的服务器上有docker了(

我写的不是用 Docker 部署 amiya 的步骤吗？

**Comment by yorisona** [comment]
> > > > > > centos7.6 可以部署吗
> > > > > 
> > > > > 
> > > > > 可以用 Docker
> > > > 
> > > > 
> > > > 有docker部署的文档嘛
> > > 
> > > 
> > > 
> > > 1. 安装 Docker：https://docs.docker.com/engine/install/centos/
> > > 2. 国内服务器可能要换源之类的
> > > 3. `docker run -it --network=host --name=amiyabot ubuntu:focal` 运行 Docker 容器
> > > 4. 在容器中 `apt update && apt install git python3-pip`
> > > 5. `cd / && git clone https://github.com/AmiyaBot/Amiya-Bot && cd Amiya-Bot`
> > > 6. 可以装个 `nano` 或者 `vim` 之类的，改一下 `requirements.txt`，把 `amiyabot` 改成 `amiyabot==1.1.19`
> > > 7. 也可以顺便改一下服务器的配置（`config/server.yaml`）
> > > 8. `pip3 install -r requirements.txt`
> > > 9. `playwright install --with-deps chromium`
> > > 10. `python3 amiya.py` 运行
> > > 
> > > 快捷键 `Ctrl-P Ctrl-Q` 断开与容器的连接，`docker attach` 连接容器，`docker exec` 可以在容器里运行别的命令。
> > 
> > 
> > > > > > centos7.6 可以部署吗
> > > > > 
> > > > > 
> > > > > 可以用 Docker
> > > > 
> > > > 
> > > > 有docker部署的文档嘛
> > > 
> > > 
> > > 
> > > 1. 安装 Docker：https://docs.docker.com/engine/install/centos/
> > > 2. 国内服务器可能要换源之类的
> > > 3. `docker run -it --network=host --name=amiyabot ubuntu:focal` 运行 Docker 容器
> > > 4. 在容器中 `apt update && apt install git python3-pip`
> > > 5. `cd / && git clone https://github.com/AmiyaBot/Amiya-Bot && cd Amiya-Bot`
> > > 6. 可以装个 `nano` 或者 `vim` 之类的，改一下 `requirements.txt`，把 `amiyabot` 改成 `amiyabot==1.1.19`
> > > 7. 也可以顺便改一下服务器的配置（`config/server.yaml`）
> > > 8. `pip3 install -r requirements.txt`
> > > 9. `playwright install --with-deps chromium`
> > > 10. `python3 amiya.py` 运行
> > > 
> > > 快捷键 `Ctrl-P Ctrl-Q` 断开与容器的连接，`docker attach` 连接容器，`docker exec` 可以在容器里运行别的命令。
> > 
> > 
> > emmm我是说docker部署amiya的文档,我的服务器上有docker了(
> 
> 我写的不是用 Docker 部署 amiya 的步骤吗？

佬我已经用docker安装好了,关于这个添加实例不是很清楚,如果我想把机器人拉倒qq群使用的话,是需要安装mirai-api-http吗

**Comment by ZhaoZuohong** [comment]
@yorisona 是的，mirai-api-http 或者 go-cqhttp 都行，接下来和 docker 关系不大了，你照着 amiya-bot 的文档弄吧

**Comment by yorisona** [comment]
> @yorisona 是的，mirai-api-http 或者 go-cqhttp 都行，接下来和 docker 关系不大了，你照着 amiya-bot 的文档弄吧

佬我配置好了go-cqhttp的实例,在插件商店安装插件时候报错如下:
2022-11-10 09:35:14,342BotERRORplugin install error: Traceback (most recent call last): 
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/log/manager.py", line 116, in sync_catch 
    yield 
  File "/usr/local/lib/python3.8/dist-packages/amiyabot/handler/__init__.py", line 274, in install_plugin 
    module = importlib.import_module(os.path.basename(dest)) 
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module 
    return _bootstrap._gcd_import(name[level:], package, level) 
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import 
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load 
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked 
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module 
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
  File "/Amiya-Bot/plugins/amiyabot-user-1_2/__init__.py", line 1, in <module> 
    from .main import bot 
  File "/Amiya-Bot/plugins/amiyabot-user-1_2/main.py", line 271, in <module> 
    @bot.timed_task(each=60) 
AttributeError: 'PluginInstance' object has no attribute 'timed_task'
