### ISSUE TITLE
关于寻访凭证的获取数量

### ISSUE THREAD

**Issue by nightmare-yudachi** [vivien8261/Amiya-Bot#6]
请问修改日签到发放的寻访凭证的数量的配置文件在哪((

**Comment by vivien8261** [comment]
@nightmare-yudachi 
[message/replies/greeting.py](https://github.com/vivien8261/Amiya-Bot/blob/master/message/replies/greeting.py) 第 9 行

```python
reward = 50
```

**Comment by nightmare-yudachi** [comment]
十分感谢
