### ISSUE TITLE
是否考虑兼容cqhttp框架呢

### ISSUE THREAD

**Issue by JMFANS** [vivien8261/Amiya-Bot#8]
因为pcr相关bot都在使用cqhttp，所以使用一个框架会不会方便些ξ( ✿＞◡❛)

**Comment by vivien8261** [comment]
@JMFANS 现在比较关键的类都是依照 mah 来设计的，切换框架比较困难，如果是兼容 CQ 码的话可能还有希望实现

**Comment by JMFANS** [comment]
![Screenshot_2021-05-13-20-21-35-775_com android chrome](https://user-images.githubusercontent.com/43535104/118125303-5fde6000-b429-11eb-8047-dc07f06b2893.jpg)

**Comment by JMFANS** [comment]
mirai那边不是听不清楚是否兼容onebot的cq码
